"""empty message

Revision ID: 01a2bc37e4ca
Revises: fd593ba87a48
Create Date: 2022-10-04 20:45:44.696757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01a2bc37e4ca'
down_revision = 'fd593ba87a48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_hari',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hari', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_mapel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mapel', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('master_tahun_ajaran',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('th_ajaran', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.String(length=1), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_tahun_ajaran')
    op.drop_table('master_mapel')
    op.drop_table('master_hari')
    # ### end Alembic commands ###
