"""empty message

Revision ID: 0c8cdd71c0d0
Revises: 454b3370ec02
Create Date: 2022-10-10 23:25:32.202519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c8cdd71c0d0'
down_revision = '454b3370ec02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_mengjar', sa.Column('kode_mengajar', sa.String(length=32), nullable=False))
    op.add_column('master_mengjar', sa.Column('guru_id', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('hari_id', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('jam_id_selesai', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('jam_id_mulai', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('semester_id', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('tahun_ajaran_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'master_mengjar', 'detail_guru', ['guru_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_hari', ['hari_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_jam_mengajar', ['jam_id_mulai'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_tahun_ajaran', ['tahun_ajaran_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_jam_mengajar', ['jam_id_selesai'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_semester', ['semester_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_column('master_mengjar', 'tahun_ajaran_id')
    op.drop_column('master_mengjar', 'semester_id')
    op.drop_column('master_mengjar', 'kelas_id')
    op.drop_column('master_mengjar', 'jam_id_mulai')
    op.drop_column('master_mengjar', 'jam_id_selesai')
    op.drop_column('master_mengjar', 'hari_id')
    op.drop_column('master_mengjar', 'guru_id')
    op.drop_column('master_mengjar', 'kode_mengajar')
    # ### end Alembic commands ###
