"""empty message

Revision ID: 1979a526b527
Revises: c12e5c22e1b2
Create Date: 2022-10-14 21:17:36.282281

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1979a526b527'
down_revision = 'c12e5c22e1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'first_name')
    op.drop_column('auth_user', 'last_name')
    op.add_column('detail_admin', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('detail_admin', sa.Column('last_name', sa.String(length=128), nullable=False))
    op.add_column('detail_guru', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('detail_guru', sa.Column('last_name', sa.String(length=128), nullable=False))
    op.add_column('detail_siswa', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('detail_siswa', sa.Column('last_name', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail_siswa', 'last_name')
    op.drop_column('detail_siswa', 'first_name')
    op.drop_column('detail_guru', 'last_name')
    op.drop_column('detail_guru', 'first_name')
    op.drop_column('detail_admin', 'last_name')
    op.drop_column('detail_admin', 'first_name')
    op.add_column('auth_user', sa.Column('last_name', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('auth_user', sa.Column('first_name', mysql.VARCHAR(length=128), nullable=False))
    # ### end Alembic commands ###
