"""empty message

Revision ID: 1bd4de386628
Revises: a87ed3903634
Create Date: 2022-10-03 10:42:13.530123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd4de386628'
down_revision = 'a87ed3903634'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_token_block',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_token_block_jti'), 'auth_token_block', ['jti'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_token_block_jti'), table_name='auth_token_block')
    op.drop_table('auth_token_block')
    # ### end Alembic commands ###
