"""empty message

Revision ID: 27ee3bcd8ffc
Revises: 0c8cdd71c0d0
Create Date: 2022-10-13 14:32:46.642900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ee3bcd8ffc'
down_revision = '0c8cdd71c0d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_siswa', sa.Column('nama_ortu_or_wali', sa.String(length=128), nullable=True))
    op.add_column('detail_siswa', sa.Column('no_telp', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail_siswa', 'no_telp')
    op.drop_column('detail_siswa', 'nama_ortu_or_wali')
    # ### end Alembic commands ###
