"""empty message

Revision ID: 2ec0f667460f
Revises: d03546b91123
Create Date: 2022-10-10 14:35:29.548318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ec0f667460f'
down_revision = 'd03546b91123'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_wali_kelas', sa.Column('guru_id', sa.Integer(), nullable=True))
    op.add_column('master_wali_kelas', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'master_wali_kelas', 'detail_guru', ['guru_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_wali_kelas', 'master_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_wali_kelas', type_='foreignkey')
    op.drop_constraint(None, 'master_wali_kelas', type_='foreignkey')
    op.drop_column('master_wali_kelas', 'kelas_id')
    op.drop_column('master_wali_kelas', 'guru_id')
    # ### end Alembic commands ###
