"""empty message

Revision ID: 3708f0f502f6
Revises: dff3c283e1ea
Create Date: 2022-10-05 19:23:17.023038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3708f0f502f6'
down_revision = 'dff3c283e1ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_semester', sa.Column('semester', sa.String(length=32), nullable=False))
    op.add_column('master_semester', sa.Column('is_active', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_semester', 'is_active')
    op.drop_column('master_semester', 'semester')
    # ### end Alembic commands ###
