"""empty message

Revision ID: 3a51e4145d87
Revises: 51a8c0d837b1
Create Date: 2022-10-10 21:21:40.828293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3a51e4145d87'
down_revision = '51a8c0d837b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detail_guru_ibfk_2', 'detail_guru', type_='foreignkey')
    op.drop_column('detail_guru', 'kelas_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_guru', sa.Column('kelas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('detail_guru_ibfk_2', 'detail_guru', 'master_kelas', ['kelas_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
