"""empty message

Revision ID: 454b3370ec02
Revises: e2afd67ace69
Create Date: 2022-10-10 23:25:18.804350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '454b3370ec02'
down_revision = 'e2afd67ace69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_mengjar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_mengjar')
    # ### end Alembic commands ###
