"""empty message

Revision ID: 4c2a7705afa5
Revises: ecc679bdfecc
Create Date: 2022-09-28 18:04:59.144515

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4c2a7705afa5'
down_revision = 'ecc679bdfecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_siswa_detail', sa.Column('first_name', sa.String(length=128), nullable=False))
    op.add_column('tb_siswa_detail', sa.Column('last_name', sa.String(length=128), nullable=False))
    op.drop_column('tb_user', 'last_name')
    op.drop_column('tb_user', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('first_name', mysql.VARCHAR(length=128), nullable=False))
    op.add_column('tb_user', sa.Column('last_name', mysql.VARCHAR(length=128), nullable=False))
    op.drop_column('tb_siswa_detail', 'last_name')
    op.drop_column('tb_siswa_detail', 'first_name')
    # ### end Alembic commands ###
