"""empty message

Revision ID: 4e9f7328cb45
Revises: b23cf39be793
Create Date: 2022-10-03 07:26:11.082595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e9f7328cb45'
down_revision = 'b23cf39be793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_guru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('alamat', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_guru')
    # ### end Alembic commands ###
