"""empty message

Revision ID: 51a8c0d837b1
Revises: fceae4cbb54e
Create Date: 2022-10-10 21:20:19.353376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51a8c0d837b1'
down_revision = 'fceae4cbb54e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_mengjar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_mengjar')
    # ### end Alembic commands ###
