"""empty message

Revision ID: 5360f48c99b3
Revises: 029986bd3295
Create Date: 2022-09-28 13:07:28.713811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5360f48c99b3'
down_revision = '029986bd3295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_user', sa.Column('id_siswa', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tb_user', 'tb_siswa_detail', ['id_siswa'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_user', type_='foreignkey')
    op.drop_column('tb_user', 'id_siswa')
    # ### end Alembic commands ###
