"""empty message

Revision ID: 5994981fbc0e
Revises: d6d99d8fa2e1
Create Date: 2022-10-13 15:33:56.863829

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5994981fbc0e'
down_revision = 'd6d99d8fa2e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_mengajar',
    sa.Column('kode_mengajar', sa.String(length=32), nullable=False),
    sa.Column('guru_id', sa.Integer(), nullable=True),
    sa.Column('hari_id', sa.Integer(), nullable=True),
    sa.Column('jam_id_selesai', sa.Integer(), nullable=True),
    sa.Column('jam_id_mulai', sa.Integer(), nullable=True),
    sa.Column('kelas_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=True),
    sa.Column('tahun_ajaran_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['guru_id'], ['detail_guru.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hari_id'], ['master_hari.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jam_id_mulai'], ['master_jam_mengajar.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jam_id_selesai'], ['master_jam_mengajar.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kelas_id'], ['master_kelas.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['master_semester.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['master_tahun_ajaran.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('master_mengjar')
    op.add_column('data_absensi', sa.Column('mengajar_id', sa.Integer(), nullable=True))
    op.add_column('data_absensi', sa.Column('siswa_id', sa.Integer(), nullable=True))
    op.add_column('data_absensi', sa.Column('tgl_absen', sa.DateTime(), nullable=True))
    op.add_column('data_absensi', sa.Column('ket', sa.String(length=16), nullable=False))
    op.add_column('data_absensi', sa.Column('pertemuan_ke', sa.String(length=2), nullable=True))
    op.create_foreign_key(None, 'data_absensi', 'master_mengajar', ['mengajar_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'data_absensi', 'detail_siswa', ['siswa_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_absensi', type_='foreignkey')
    op.drop_constraint(None, 'data_absensi', type_='foreignkey')
    op.drop_column('data_absensi', 'pertemuan_ke')
    op.drop_column('data_absensi', 'ket')
    op.drop_column('data_absensi', 'tgl_absen')
    op.drop_column('data_absensi', 'siswa_id')
    op.drop_column('data_absensi', 'mengajar_id')
    op.create_table('master_mengjar',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('kode_mengajar', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('guru_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hari_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('jam_id_selesai', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('jam_id_mulai', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('kelas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('semester_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('tahun_ajaran_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['guru_id'], ['detail_guru.id'], name='master_mengjar_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hari_id'], ['master_hari.id'], name='master_mengjar_ibfk_2', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jam_id_mulai'], ['master_jam_mengajar.id'], name='master_mengjar_ibfk_3', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['jam_id_selesai'], ['master_jam_mengajar.id'], name='master_mengjar_ibfk_5', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kelas_id'], ['master_kelas.id'], name='master_mengjar_ibfk_6', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['semester_id'], ['master_semester.id'], name='master_mengjar_ibfk_7', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tahun_ajaran_id'], ['master_tahun_ajaran.id'], name='master_mengjar_ibfk_4', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('master_mengajar')
    # ### end Alembic commands ###
