"""empty message

Revision ID: 5cc22d821325
Revises: 911af50bdfda
Create Date: 2022-10-04 22:12:54.817401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5cc22d821325'
down_revision = '911af50bdfda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_kelas')
    op.drop_table('detail_admin')
    op.add_column('auth_user', sa.Column('gender', sa.String(length=32), nullable=True))
    op.add_column('auth_user', sa.Column('alamat', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'alamat')
    op.drop_column('auth_user', 'gender')
    op.create_table('detail_admin',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('alamat', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='detail_admin_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_kelas',
    sa.Column('kelas_ID', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_kelas', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('jml_siswa', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('jml_laki', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('jml_perempuan', mysql.VARCHAR(length=16), nullable=True),
    sa.PrimaryKeyConstraint('kelas_ID'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
