"""empty message

Revision ID: 5dfc0b93a66b
Revises: af53b59b00b1
Create Date: 2022-10-05 17:35:04.553065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dfc0b93a66b'
down_revision = 'af53b59b00b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_semester',
    sa.Column('semester', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_semester')
    # ### end Alembic commands ###
