"""empty message

Revision ID: 5e36d11a92a8
Revises: 5cc22d821325
Create Date: 2022-10-04 22:14:21.221306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e36d11a92a8'
down_revision = '5cc22d821325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auth_user', 'auth_user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'auth_user', type_='foreignkey')
    op.drop_column('auth_user', 'user_id')
    # ### end Alembic commands ###
