"""empty message

Revision ID: 6b88bd436b8d
Revises: 1979a526b527
Create Date: 2022-10-15 01:44:37.858376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b88bd436b8d'
down_revision = '1979a526b527'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_siswa', sa.Column('pic', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail_siswa', 'pic')
    # ### end Alembic commands ###
