"""empty message

Revision ID: 737d288b7b64
Revises: a574d27ae8b5
Create Date: 2022-10-10 14:48:19.248440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '737d288b7b64'
down_revision = 'a574d27ae8b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detail_siswa_ibfk_2', 'detail_siswa', type_='foreignkey')
    op.drop_column('detail_siswa', 'kelas_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_siswa', sa.Column('kelas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('detail_siswa_ibfk_2', 'detail_siswa', 'master_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
