"""empty message

Revision ID: 742c54d47bcb
Revises: 5dfc0b93a66b
Create Date: 2022-10-05 17:40:01.584561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742c54d47bcb'
down_revision = '5dfc0b93a66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_semester', sa.Column('is_active', sa.String(length=1), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_semester', 'is_active')
    # ### end Alembic commands ###
