"""empty message

Revision ID: 89ff083b9aa7
Revises: 8bac18c37f8c
Create Date: 2022-10-13 15:41:15.168808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89ff083b9aa7'
down_revision = '8bac18c37f8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_absensi')
    # ### end Alembic commands ###
