"""empty message

Revision ID: 8bac18c37f8c
Revises: 5994981fbc0e
Create Date: 2022-10-13 15:40:29.696778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bac18c37f8c'
down_revision = '5994981fbc0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_absensi',
    sa.Column('mengajar_id', sa.Integer(), nullable=True),
    sa.Column('siswa_id', sa.Integer(), nullable=True),
    sa.Column('tgl_absen', sa.Date(), nullable=True),
    sa.Column('ket', sa.String(length=16), nullable=False),
    sa.Column('pertemuan_ke', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mengajar_id'], ['master_mengajar.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['siswa_id'], ['detail_siswa.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_absensi')
    # ### end Alembic commands ###
