"""empty message

Revision ID: 906b3477e94e
Revises: 75cef3be3e36
Create Date: 2022-10-04 20:39:04.419159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906b3477e94e'
down_revision = '75cef3be3e36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=16), nullable=False),
    sa.Column('jml_laki', sa.String(length=2), nullable=True),
    sa.Column('jml_perempuan', sa.String(length=2), nullable=True),
    sa.Column('jml_seluruh', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kelas')
    # ### end Alembic commands ###
