"""empty message

Revision ID: 911af50bdfda
Revises: 9f03971d4701
Create Date: 2022-10-04 21:22:20.508186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '911af50bdfda'
down_revision = '9f03971d4701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_guru', sa.Column('mapel_id', sa.Integer(), nullable=True))
    op.add_column('detail_guru', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detail_guru', 'master_kelas', ['kelas_id'], ['id'])
    op.create_foreign_key(None, 'detail_guru', 'master_mapel', ['mapel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail_guru', type_='foreignkey')
    op.drop_constraint(None, 'detail_guru', type_='foreignkey')
    op.drop_column('detail_guru', 'kelas_id')
    op.drop_column('detail_guru', 'mapel_id')
    # ### end Alembic commands ###
