"""empty message

Revision ID: 9eef6378ee2b
Revises: b6732970c6f4
Create Date: 2022-10-10 21:41:05.047213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eef6378ee2b'
down_revision = 'b6732970c6f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_jam_mengajar', sa.Column('jam', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_jam_mengajar', 'jam')
    # ### end Alembic commands ###
