"""empty message

Revision ID: 9f03971d4701
Revises: 01a2bc37e4ca
Create Date: 2022-10-04 20:48:03.870535

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f03971d4701'
down_revision = '01a2bc37e4ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('alamat', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_guru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('agama', sa.String(length=32), nullable=True),
    sa.Column('alamat', sa.String(length=256), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detail_siswa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=128), nullable=True),
    sa.Column('tgl_lahir', sa.Date(), nullable=True),
    sa.Column('agama', sa.String(length=128), nullable=False),
    sa.Column('alamat', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tb_guru_detail')
    op.drop_table('admin_detail')
    op.drop_table('tb_siswa_detail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_siswa_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('tempat_lahir', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('tgl_lahir', sa.DATE(), nullable=True),
    sa.Column('agama', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('alamat', mysql.VARCHAR(length=250), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='tb_siswa_detail_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('admin_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('alamat', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='admin_detail_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('tb_guru_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('alamat', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('agama', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], name='tb_guru_detail_ibfk_1', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('detail_siswa')
    op.drop_table('detail_guru')
    op.drop_table('detail_admin')
    # ### end Alembic commands ###
