"""empty message

Revision ID: a574d27ae8b5
Revises: b838586c3fba
Create Date: 2022-10-10 14:41:50.345970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a574d27ae8b5'
down_revision = 'b838586c3fba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_guru', sa.Column('mapel_id', sa.Integer(), nullable=True))
    op.add_column('detail_guru', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detail_guru', 'master_kelas', ['kelas_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detail_guru', 'master_mapel', ['mapel_id'], ['id'], ondelete='CASCADE')
    op.add_column('detail_siswa', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detail_siswa', 'master_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail_siswa', type_='foreignkey')
    op.drop_column('detail_siswa', 'kelas_id')
    op.drop_constraint(None, 'detail_guru', type_='foreignkey')
    op.drop_constraint(None, 'detail_guru', type_='foreignkey')
    op.drop_column('detail_guru', 'kelas_id')
    op.drop_column('detail_guru', 'mapel_id')
    # ### end Alembic commands ###
