"""empty message

Revision ID: a87ed3903634
Revises: ccff8544d588
Create Date: 2022-10-03 07:35:37.694814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87ed3903634'
down_revision = 'ccff8544d588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_guru_detail', sa.Column('agama', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tb_guru_detail', 'agama')
    # ### end Alembic commands ###
