"""empty message

Revision ID: af53b59b00b1
Revises: c4daf4bdb0c9
Create Date: 2022-10-05 07:44:01.000792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af53b59b00b1'
down_revision = 'c4daf4bdb0c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detail_admin_ibfk_1', 'detail_admin', type_='foreignkey')
    op.create_foreign_key(None, 'detail_admin', 'auth_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('detail_guru_ibfk_2', 'detail_guru', type_='foreignkey')
    op.drop_constraint('detail_guru_ibfk_3', 'detail_guru', type_='foreignkey')
    op.create_foreign_key(None, 'detail_guru', 'master_mapel', ['mapel_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detail_guru', 'master_kelas', ['kelas_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail_guru', type_='foreignkey')
    op.drop_constraint(None, 'detail_guru', type_='foreignkey')
    op.create_foreign_key('detail_guru_ibfk_3', 'detail_guru', 'master_mapel', ['mapel_id'], ['id'])
    op.create_foreign_key('detail_guru_ibfk_2', 'detail_guru', 'master_kelas', ['kelas_id'], ['id'])
    op.drop_constraint(None, 'detail_admin', type_='foreignkey')
    op.create_foreign_key('detail_admin_ibfk_1', 'detail_admin', 'auth_user', ['user_id'], ['id'])
    # ### end Alembic commands ###
