"""empty message

Revision ID: b23cf39be793
Revises: 
Create Date: 2022-10-03 06:46:33.974160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23cf39be793'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('group', sa.String(length=128), nullable=False),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.Column('update_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.String(length=2), nullable=False),
    sa.Column('user_login_now', sa.DateTime(), nullable=True),
    sa.Column('user_logout', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_siswa_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=32), nullable=False),
    sa.Column('tempat_lahir', sa.String(length=128), nullable=True),
    sa.Column('tgl_lahir', sa.Date(), nullable=True),
    sa.Column('agama', sa.String(length=128), nullable=False),
    sa.Column('alamat', sa.String(length=250), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['tb_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_siswa_detail')
    op.drop_table('tb_user')
    # ### end Alembic commands ###
