"""empty message

Revision ID: b6732970c6f4
Revises: 3a51e4145d87
Create Date: 2022-10-10 21:30:21.851480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6732970c6f4'
down_revision = '3a51e4145d87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_jam_mengajar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_jam_mengajar')
    # ### end Alembic commands ###
