"""empty message

Revision ID: b838586c3fba
Revises: 2ec0f667460f
Create Date: 2022-10-10 14:32:39.863806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b838586c3fba'
down_revision = '2ec0f667460f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detail_guru_ibfk_2', 'detail_guru', type_='foreignkey')
    op.drop_constraint('detail_guru_ibfk_3', 'detail_guru', type_='foreignkey')
    op.drop_column('detail_guru', 'mapel_id')
    op.drop_column('detail_guru', 'kelas_id')
    op.drop_constraint('detail_siswa_ibfk_2', 'detail_siswa', type_='foreignkey')
    op.drop_column('detail_siswa', 'kelas_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_siswa', sa.Column('kelas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('detail_siswa_ibfk_2', 'detail_siswa', 'master_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.add_column('detail_guru', sa.Column('kelas_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('detail_guru', sa.Column('mapel_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('detail_guru_ibfk_3', 'detail_guru', 'master_kelas', ['kelas_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('detail_guru_ibfk_2', 'detail_guru', 'master_mapel', ['mapel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
