"""empty message

Revision ID: bb368b6915c1
Revises: 6b88bd436b8d
Create Date: 2022-10-30 13:29:47.712207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb368b6915c1'
down_revision = '6b88bd436b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'detail_siswa', 'master_kelas', ['kelas_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail_siswa', type_='foreignkey')
    # ### end Alembic commands ###
