"""empty message

Revision ID: c12e5c22e1b2
Revises: 89ff083b9aa7
Create Date: 2022-10-13 15:41:23.661563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12e5c22e1b2'
down_revision = '89ff083b9aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_absensi', sa.Column('mengajar_id', sa.Integer(), nullable=True))
    op.add_column('data_absensi', sa.Column('siswa_id', sa.Integer(), nullable=True))
    op.add_column('data_absensi', sa.Column('tgl_absen', sa.Date(), nullable=True))
    op.add_column('data_absensi', sa.Column('ket', sa.String(length=16), nullable=False))
    op.add_column('data_absensi', sa.Column('pertemuan_ke', sa.String(length=2), nullable=True))
    op.create_foreign_key(None, 'data_absensi', 'detail_siswa', ['siswa_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'data_absensi', 'master_mengajar', ['mengajar_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data_absensi', type_='foreignkey')
    op.drop_constraint(None, 'data_absensi', type_='foreignkey')
    op.drop_column('data_absensi', 'pertemuan_ke')
    op.drop_column('data_absensi', 'ket')
    op.drop_column('data_absensi', 'tgl_absen')
    op.drop_column('data_absensi', 'siswa_id')
    op.drop_column('data_absensi', 'mengajar_id')
    # ### end Alembic commands ###
