"""empty message

Revision ID: c4daf4bdb0c9
Revises: 5e36d11a92a8
Create Date: 2022-10-04 22:15:14.726782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4daf4bdb0c9'
down_revision = '5e36d11a92a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detail_admin',
    sa.Column('gender', sa.String(length=32), nullable=True),
    sa.Column('alamat', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('auth_user_ibfk_1', 'auth_user', type_='foreignkey')
    op.drop_column('auth_user', 'user_id')
    op.drop_column('auth_user', 'alamat')
    op.drop_column('auth_user', 'gender')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('gender', mysql.VARCHAR(length=32), nullable=True))
    op.add_column('auth_user', sa.Column('alamat', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('auth_user', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('auth_user_ibfk_1', 'auth_user', 'auth_user', ['user_id'], ['id'])
    op.drop_table('detail_admin')
    # ### end Alembic commands ###
