"""empty message

Revision ID: d03546b91123
Revises: fc9006622aa5
Create Date: 2022-10-10 14:31:20.072846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03546b91123'
down_revision = 'fc9006622aa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_wali_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_wali_kelas')
    # ### end Alembic commands ###
