"""empty message

Revision ID: d6d99d8fa2e1
Revises: 27ee3bcd8ffc
Create Date: 2022-10-13 15:10:24.458717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d99d8fa2e1'
down_revision = '27ee3bcd8ffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_absensi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_absensi')
    # ### end Alembic commands ###
