"""empty message

Revision ID: dff3c283e1ea
Revises: 742c54d47bcb
Create Date: 2022-10-05 19:22:53.001624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff3c283e1ea'
down_revision = '742c54d47bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('master_semester')
    # ### end Alembic commands ###
