"""empty message

Revision ID: e2afd67ace69
Revises: ef17c0a73af7
Create Date: 2022-10-10 23:23:40.073582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2afd67ace69'
down_revision = 'ef17c0a73af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_mengjar', sa.Column('guru_id', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('semester_id', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('tahun_ajaran_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'master_mengjar', 'master_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'detail_guru', ['guru_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_semester', ['semester_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_tahun_ajaran', ['tahun_ajaran_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_column('master_mengjar', 'tahun_ajaran_id')
    op.drop_column('master_mengjar', 'semester_id')
    op.drop_column('master_mengjar', 'kelas_id')
    op.drop_column('master_mengjar', 'guru_id')
    # ### end Alembic commands ###
