"""empty message

Revision ID: e2fec572e619
Revises: 2b15bef33b75
Create Date: 2022-10-10 08:08:08.441720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2fec572e619'
down_revision = '2b15bef33b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('user_last_login', sa.DateTime(), nullable=True))
    op.drop_column('auth_user', 'user_login_now')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('user_login_now', mysql.DATETIME(), nullable=True))
    op.drop_column('auth_user', 'user_last_login')
    # ### end Alembic commands ###
