"""empty message

Revision ID: e9e3051c2008
Revises: bb368b6915c1
Create Date: 2022-11-04 07:07:24.256104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9e3051c2008'
down_revision = 'bb368b6915c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_guru', sa.Column('telp', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detail_guru', 'telp')
    # ### end Alembic commands ###
