"""empty message

Revision ID: ea6373b05b74
Revises: bad6341b8881
Create Date: 2022-09-28 13:39:57.627348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6373b05b74'
down_revision = 'bad6341b8881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tb_siswa_detail', sa.Column('gender', sa.Enum('perempuan', 'laki-laki'), nullable=True))
    op.add_column('tb_siswa_detail', sa.Column('tempat_lahir', sa.String(length=128), nullable=True))
    op.add_column('tb_siswa_detail', sa.Column('tgl_lahir', sa.Date(), nullable=True))
    op.add_column('tb_siswa_detail', sa.Column('agama', sa.Enum('islam', 'kristen', 'hindu', 'hindu', 'budha'), nullable=True))
    op.drop_constraint('tb_user_ibfk_1', 'tb_user', type_='foreignkey')
    op.create_foreign_key(None, 'tb_user', 'tb_siswa_detail', ['id_siswa'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tb_user', type_='foreignkey')
    op.create_foreign_key('tb_user_ibfk_1', 'tb_user', 'tb_siswa_detail', ['id_siswa'], ['id'])
    op.drop_column('tb_siswa_detail', 'agama')
    op.drop_column('tb_siswa_detail', 'tgl_lahir')
    op.drop_column('tb_siswa_detail', 'tempat_lahir')
    op.drop_column('tb_siswa_detail', 'gender')
    # ### end Alembic commands ###
