"""empty message

Revision ID: ecc679bdfecc
Revises: 132dfa8169a5
Create Date: 2022-09-28 16:21:47.487333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ecc679bdfecc'
down_revision = '132dfa8169a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_siswa_detail', 'gender',
               existing_type=mysql.ENUM('perempuan', 'laki-laki'),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_siswa_detail', 'gender',
               existing_type=mysql.ENUM('perempuan', 'laki-laki'),
               nullable=True)
    # ### end Alembic commands ###
