"""empty message

Revision ID: ef17c0a73af7
Revises: 9eef6378ee2b
Create Date: 2022-10-10 23:12:12.544131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef17c0a73af7'
down_revision = '9eef6378ee2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_mengjar', sa.Column('kode_mengajar', sa.String(length=32), nullable=False))
    op.add_column('master_mengjar', sa.Column('jam_id_mulai', sa.Integer(), nullable=True))
    op.add_column('master_mengjar', sa.Column('jam_id_selesai', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'master_mengjar', 'master_jam_mengajar', ['jam_id_selesai'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'master_mengjar', 'master_jam_mengajar', ['jam_id_mulai'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_constraint(None, 'master_mengjar', type_='foreignkey')
    op.drop_column('master_mengjar', 'jam_id_selesai')
    op.drop_column('master_mengjar', 'jam_id_mulai')
    op.drop_column('master_mengjar', 'kode_mengajar')
    # ### end Alembic commands ###
