"""empty message

Revision ID: f3f89e0fba6c
Revises: 4c2a7705afa5
Create Date: 2022-09-28 20:51:51.530810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3f89e0fba6c'
down_revision = '4c2a7705afa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_user', 'is_active',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tb_user', 'is_active',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###
