"""empty message

Revision ID: fc9006622aa5
Revises: e2fec572e619
Create Date: 2022-10-10 10:51:23.937299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc9006622aa5'
down_revision = 'e2fec572e619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detail_siswa', sa.Column('kelas_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'detail_siswa', 'master_kelas', ['kelas_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail_siswa', type_='foreignkey')
    op.drop_column('detail_siswa', 'kelas_id')
    # ### end Alembic commands ###
