"""empty message

Revision ID: fd593ba87a48
Revises: 906b3477e94e
Create Date: 2022-10-04 20:40:07.116307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd593ba87a48'
down_revision = '906b3477e94e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_kelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kelas', sa.String(length=16), nullable=False),
    sa.Column('jml_laki', sa.String(length=2), nullable=True),
    sa.Column('jml_perempuan', sa.String(length=2), nullable=True),
    sa.Column('jml_seluruh', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('kelas')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kelas',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('kelas', mysql.VARCHAR(length=16), nullable=False),
    sa.Column('jml_laki', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('jml_perempuan', mysql.VARCHAR(length=2), nullable=True),
    sa.Column('jml_seluruh', mysql.VARCHAR(length=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('master_kelas')
    # ### end Alembic commands ###
